# Generated by Django 4.1.5 on 2023-08-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_custuser_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custuser',
            name='usertype',
        ),
    ]
