# Generated by Django 4.1.5 on 2023-08-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_custuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='usertype',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='', max_length=100),
        ),
    ]
