# Generated by Django 4.1.5 on 2023-08-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_custuser_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='usertype',
            field=models.CharField(choices=[('Admin', 'Admin'), ('customer', 'customer')], max_length=100, null=True),
        ),
    ]
