# Generated by Django 4.1.5 on 2023-08-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_custuser_usertype_custuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='custuser',
            name='usertype',
            field=models.CharField(choices=[('Admin', 'Admin'), ('customer', 'customer')], max_length=100, null=True),
        ),
    ]
