# Generated by Django 4.1.5 on 2023-08-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Two Wheelers', 'Two Wheelers'), ('Three Wheelers', 'Three Wheelers'), ('Four Wheelers', 'Four Wheelers')], default='', max_length=100),
        ),
    ]
