# Generated by Django 4.1.5 on 2023-08-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Two Wheelers', 'Two Wheelers'), ('Three Wheelers', 'Three Wheelers'), ('Four Wheelers', 'Four Wheelers')], default='Two Wheelers', max_length=100),
        ),
    ]
